### ISSUE TITLE
Implement setting to define a specific user for course exports

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-local_remote_backup_provider#10]
Right now the plugin is configured like that. We have a **local** Moodle (where we want to import courses) and a **remote** Moodle where the courses are stored. 
Right now the local user clicks on "Import from remote", then searches a course via a search form. Usually the user on the remote is the same like on the local moodle (username or email matches). And the search is done over all courses the user has access to.
When activating the new feature, this will be different: The search will be done with the user chosen in the setting. Also the user has to have the rights to create a backup for the courses. So no matter which user on the local instance wants to import a course, on the remote it is always the courses the user specified in the settings defines which courses can be backed up. (This depends on the permissions of the user)

**Comment by bernhard-wunderbyte** [comment]
- [x] Implement the feature: Done
